# Generated by Django 4.0.6 on 2022-09-24 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remainder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remainder',
            name='duration',
            field=models.DateTimeField(),
        ),
    ]
