# Generated by Django 4.0.6 on 2022-09-24 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remainder', '0002_alter_remainder_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remainder',
            name='duration',
            field=models.DateField(),
        ),
    ]
