# Generated by Django 4.0.6 on 2022-09-24 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remainder', '0003_alter_remainder_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='remainder',
            name='color',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
